<?php

namespace App\Libraries;

use Dompdf\Dompdf;
use Dompdf\Options;

class PDFExporter
{
    protected $dompdf;
    protected $options;

    public function __construct()
    {
        $this->options = new Options();
        $this->options->set('isHtml5ParserEnabled', true);
        $this->options->set('isRemoteEnabled', true);
        
        $this->dompdf = new Dompdf($this->options);
    }

    /**
     * Generate dashboard report PDF
     * 
     * @param array $data Dashboard data
     * @return string PDF file path or content
     */
    public function generateDashboardReport(array $data): string
    {
        $html = $this->buildDashboardHTML($data);
        
        $this->dompdf->loadHtml($html);
        $this->dompdf->setPaper('A4', 'portrait');
        $this->dompdf->render();
        
        return $this->dompdf->output();
    }

    /**
     * Build HTML for dashboard report
     * 
     * @param array $data Dashboard data
     * @return string HTML content
     */
    protected function buildDashboardHTML(array $data): string
    {
        $html = '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Dashboard Report</title>
            <style>
                body { font-family: Arial, sans-serif; font-size: 12px; }
                h1 { text-align: center; color: #333; }
                table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background-color: #4CAF50; color: white; }
                .stats { display: flex; justify-content: space-around; margin: 20px 0; }
                .stat-box { text-align: center; padding: 15px; border: 1px solid #ddd; }
                .stat-number { font-size: 24px; font-weight: bold; color: #4CAF50; }
                .footer { text-align: center; margin-top: 30px; font-size: 10px; color: #666; }
            </style>
        </head>
        <body>
            <h1>Laporan Dashboard Tracking Training</h1>
            <p><strong>Tanggal:</strong> ' . date('d F Y H:i') . '</p>
            
            <h2>Statistik Umum</h2>
            <table>
                <tr>
                    <th>Metrik</th>
                    <th>Nilai</th>
                </tr>
                <tr>
                    <td>Total Users</td>
                    <td>' . ($data['total_users'] ?? 0) . '</td>
                </tr>
                <tr>
                    <td>Active Users</td>
                    <td>' . ($data['active_users'] ?? 0) . '</td>
                </tr>
                    <td>Pending Users</td>
                    <td>' . ($data['pending_users'] ?? 0) . '</td>
                <tr>
                    <td>Training Completion Rate</td>
                    <td>' . ($data['completion_rate'] ?? 0) . '%</td>
                </tr>
            </table>
            
            <h2>Distribusi BMI</h2>
            <table>
                <tr>
                    <th>Kategori</th>
                    <th>Jumlah User</th>
                </tr>';
        
        foreach ($data['bmi_stats'] ?? [] as $stat) {
            $html .= '<tr>
                        <td>' . ucfirst($stat['bmi_category']) . '</td>
                        <td>' . $stat['count'] . '</td>
                      </tr>';
        }
        
        $html .= '
            </table>
            
            <div class="footer">
                <p>Generated by Tracking Training App | © 2025</p>
            </div>
        </body>
        </html>';
        
        return $html;
    }

    /**
     * Download PDF file
     * 
     * @param string $content PDF content
     * @param string $filename File name
     * @return void
     */
    public function download(string $content, string $filename = 'report.pdf'): void
    {
        header('Content-Type: application/pdf');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        echo $content;
        exit;
    }

    /**
     * Save PDF to file
     * 
     * @param string $content PDF content
     * @param string $filepath File path
     * @return bool Success status
     */
    public function save(string $content, string $filepath): bool
    {
        return file_put_contents($filepath, $content) !== false;
    }
}